spring.application.name=SB-EMS
#Embedded Tomcat Port Number
server.port=1234

#DataBase Connection Properties

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/testdata

# Database Username
spring.datasource.username=root

# Database Password
spring.datasource.password=sairoop@1551

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

ems.save.success = "SUCCESS : Employee Object saved"
ems.db.fail = "FAILED : DB Error"
ems.update.success = "SUCCESS : Employee UPDATED"
ems.delete.success = "SUCCESS : Employee Deleted"

#Application Error Properties

ems.invalid.employee-details = "FAILED : Invalid Employee Details"
ems.invalid.employee-notfound = "FAILED : Employee Details NOT FOUND"
