spring.application.name=SB-DMS-SERVICE

#Embedded Tomcat Port Number
server.port=2222


eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


#DataBase Connection Properties

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/testdata

# Database Username
spring.datasource.username=root

# Database Password
spring.datasource.password=sairoop@1551

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

dms.department.dberror=FAILURE : DB Error Occured
dms.department.add.success=SUCCESS : Department Added Successfully
dms.department.update.success=SUCCESS : Department Updated Successfully
dms.department.delete.success=SUCCESS : Department Deleted Successfully
dms.department.notfound=FAILURE : Department Not Found
dms.invalid.notfound=FAILURE : Department Not Found

